version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
    networks:
      - elastic
    restart: unless-stopped
volumes:
  esdata1:
    driver: local
networks:
  elastic: