# Generated by Django 4.2.5 on 2023-09-20 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tags', models.ManyToManyField(to='docsapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Editable',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.TimeField()),
                ('restricted', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docsapp.user')),
                ('read_tags', models.ManyToManyField(related_name='readable', to='docsapp.tag')),
                ('write_tags', models.ManyToManyField(related_name='writeable', to='docsapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('lineno', models.BigIntegerField()),
                ('parent_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docsapp.editable')),
            ],
        ),
    ]
