# Generated by Django 4.2.5 on 2023-09-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0002_alter_editable_content_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='docsapp.editable'),
        ),
    ]
