# Generated by Django 4.2.5 on 2023-09-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0003_alter_comment_parent_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docsapp.editable'),
        ),
    ]
