# Generated by Django 4.2.5 on 2023-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0005_alter_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
