# Generated by Django 4.2.5 on 2023-10-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0007_tag_creator_alter_editable_slug_alter_tag_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='creator',
        ),
    ]
