# Generated by Django 4.2.5 on 2023-10-06 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docsapp', '0009_rename_user_userprofile_comment_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_of',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
