# Generated by Django 4.2.5 on 2023-10-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0010_userprofile_profile_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_of',
            new_name='profile',
        ),
    ]
