# Generated by Django 4.2.5 on 2023-10-06 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docsapp', '0012_remove_userprofile_profile_userprofile_profile_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_of',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
