# Generated by Django 4.2.5 on 2023-10-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0014_profile_alter_comment_commenter_alter_editable_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_of',
            new_name='user',
        ),
    ]
