# Generated by Django 4.2.5 on 2023-10-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0015_rename_profile_of_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editable',
            name='creation_time',
        ),
    ]
