# Generated by Django 4.2.5 on 2023-10-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0018_rename_owner_editable_creator_tag_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editable',
            name='content',
            field=models.BinaryField(),
        ),
    ]
