# Generated by Django 4.2.5 on 2023-10-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0021_alter_editable_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editable',
            name='restricted',
        ),
    ]
