# Generated by Django 4.2.5 on 2023-11-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0024_tag_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
