# Generated by Django 4.2.5 on 2023-11-04 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0025_editable_restricted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lineno',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='docsapp.editable'),
        ),
    ]
