# Generated by Django 4.2.5 on 2023-11-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0026_remove_comment_id_remove_comment_lineno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='docsapp.editable'),
        ),
    ]
