# Generated by Django 4.2.5 on 2023-11-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0027_alter_comment_parent_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable',
            name='accessors',
            field=models.ManyToManyField(blank=True, related_name='accessibles', to='docsapp.profile'),
        ),
    ]
