# Generated by Django 4.2.5 on 2023-11-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0028_editable_accessors'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable',
            name='content_text',
            field=models.CharField(blank=True),
        ),
    ]
