# Generated by Django 4.2.5 on 2023-11-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0029_editable_content_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editable',
            old_name='content_text',
            new_name='contenttext',
        ),
    ]
